
export const translations = {
  pt: {
    dashboard: 'Dashboard',
    projectDetails: 'Detalhes do Projeto',
    projectSetup: 'Configuração do Projeto',
    projectSettings: 'Configurações do Projeto',
    dataInput: 'Entrada de Dados',
    reserveAnalysis: 'Análise de Reservas',
    graphicalAnalysis: 'Análise Gráfica',
    financialAnalysis: 'Viabilidade Econômica',
    comparisonBlocks: 'Comparação/Blocos',
    aiReport: 'Relatório IA',
    heatmap: 'Mapa de Calor',
    statistics: 'Estatísticas',
    statisticalAnalysis: 'Análise Estatística',
    gradeHistogram: 'Histograma de Teores',
    gradeCurve: 'Curva Grade-Tonnage',
    boxplotStats: 'Estatísticas Descritivas (Boxplot)',
    romAnalysis: 'Análise ROM (Produção)',
    theme: 'Tema',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Escuro',
    portuguese: 'Português',
    english: 'Inglês',
    spanish: 'Espanhol',
    userName: 'Nome de Usuário',
    blockId: 'ID do Bloco',
    projectName: 'Nome do Projeto',
    projectDescription: 'Descrição do Projeto',
    date: 'Data',
    sampleDataTable: 'Tabela de Dados de Amostras',
    swellFactorSterile: 'Fator de Empolamento (Estéril)',
    swellFactorGravel: 'Fator de Empolamento (Cascalho)',
    dilutionFactor: 'Fator de Diluição (%)',
    importCSV: 'Importar CSV/XLSX',
    addSample: 'Adicionar Amostra',
    validateData: 'Validar Dados',
    no: 'Nº',
    line: 'Linha',
    pit: 'Poço',
    sterileDepth: 'Estéril (m)',
    gravelDepth: 'Cascalho (m)',
    area: 'Área (m²)',
    volume: 'Volume (m³)',
    stones: 'Pedras',
    carats: 'Quilates',
    actions: 'Ações',
    remove: 'Remover',
    estimatedReserves: 'Reservas Estimadas',
    prospectingData: 'Dados de Prospecção',
    totalPitArea: 'Área Total dos Poços (m²)',
    avgSterileDepth: 'Espessura Média Estéril (m)',
    avgGravelDepth: 'Espessura Média Cascalho (m)',
    totalStones: 'Nº Total de Pedras',
    totalCarats: 'Quilates Totais',
    stonesPerSqm: 'Pedras/m²',
    avgStoneSize: 'Tamanho Médio da Pedra (ct)',
    inSituReserves: 'Reservas In Situ',
    sterileVolume: 'Volume Estéril (m³)',
    gravelVolume: 'Volume Cascalho (m³)',
    estimatedCarats: 'Quilates Estimados',
    caratsPerSqm: 'Quilates/m²',
    caratsPerCbm: 'Quilates/m³',
    estimatedStones: 'Nº de Pedras Estimadas',
    swelledDilutedReserves: 'Reservas Empoladas e Diluídas',
    swelledSterileVolume: 'Volume Estéril Empolado (m³)',
    swelledGravelVolume: 'Volume Cascalho Empolado (m³)',
    avgGrade: 'Teor Médio (ct/m³)',
    stripRatio: 'Relação Estéril/Minério (S/R)',
    chartsAndSensitivity: 'Gráficos e Sensibilidade',
    volumeComparison: 'Comparação de Volume (In Situ vs Empolado)',
    inSitu: 'In Situ',
    swelled: 'Empolado',
    sterile: 'Estéril',
    gravel: 'Cascalho',
    swelledReserveDistribution: 'Distribuição de Reserva Empolada',
    gradeVariationByPit: 'Variação de Teor por Poço (ct/m³)',
    gradeVsGravelDepth: 'Teor (ct/m³) vs. Espessura Cascalho (m)',
    gradeVsArea: 'Teor (ct/m³) vs. Área (m²)',
    economicParameters: 'Parâmetros Econômicos',
    diamondPrice: 'Preço Médio do Diamante (USD/ct)',
    sterileRemovalCost: 'Custo Remoção Estéril (USD/m³)',
    gravelTransportCost: 'Custo Transporte Cascalho (USD/m³/km)',
    processingCost: 'Custo Tratamento (USD/m³)',
    transportDistance: 'Distância até Lavaria (km)',
    recoveryRate: 'Taxa de Recuperação (%)',
    blockEconomy: 'Economia do Bloco',
    recoveredCarats: 'Quilates Recuperados',
    estimatedRevenue: 'Receita Estimada (USD)',
    totalCost: 'Custo Total (USD)',
    estimatedProfit: 'Lucro Estimado (USD)',
    economicViability: 'Viabilidade Econômica',
    projectViable: 'Projeto Viável',
    projectNotViable: 'Projeto Não Viável',
    sensitivityAnalysis: 'Análise de Sensibilidade',
    generateReport: 'Gerar Relatório IA',
    generating: 'Gerando...',
    report: 'Relatório',
    copyToClipboard: 'Copiar para Área de Transferência',
    copied: 'Copiado!',
    mineralReserveReportFor: 'Relatório de Reserva Mineral para',
    totalBlockArea: 'Área Total do Bloco (m²)',
    geotechnicalParameters: 'Parámetros Geotécnicos',
    save: 'Guardar',
    saved: 'Guardado!',
    manageProjects: 'Gerenciar Projetos',
    newProject: 'Novo Projeto',
    saveProject: 'Guardar Projeto',
    deleteProject: 'Deletar Projeto',
    confirmDelete: 'Você tem certeza que quer deletar este projeto?',
    creatingNewProject: 'Criando Novo Projeto',
    editingProject: 'Editando Projeto',
    chartSettings: 'Configurações de Gráfico',
    chartColors: 'Cores do Gráfico',
    showTooltips: 'Mostrar Dicas',
    inSituColor: 'Cor In Situ',
    swelledColor: 'Cor Empolado',
    sterileColor: 'Cor Estéril',
    gravelColor: 'Cor Cascalho',
    gradeColor: 'Cor do Teor',
    scatterDepthColor: 'Cor Dispersão (Profundidade)',
    scatterAreaColor: 'Cor Dispersão (Área)',
    reset: 'Redefinir',
    edit: 'Editar',
    unsavedChanges: 'Alterações não salvas',
    saveChanges: 'Salvar Alterações',
    discardChanges: 'Descartar',
    confirmNavigation: 'Você tem alterações não salvas. Deseja salvar ou descartar antes de sair?',
    bulkEdit: 'Edição em Massa',
    selectField: 'Selecionar Campo',
    operation: 'Operación',
    setValue: 'Definir Valor',
    addValue: 'Adicionar',
    apply: 'Aplicar',
    currency: 'Moeda',
    unitSystem: 'Sistema de Unidades',
    metric: 'Métrico',
    imperial: 'Imperial',
    defaultCurrency: 'Moeda Padrão',
    economicComparison: 'Comparação Económica',
    profitabilityComparison: 'Comparativo de Lucratividade',
    revenue: 'Receita',
    cost: 'Custo',
    profit: 'Lucro',
    roi: 'Retorno (ROI %)',
    loadingData: 'Carregando Dados...',
    selectProjectsToCompare: 'Selecione os Projetos para Comparar',
    copyData: 'Copiar Dados (CSV)',
    analyzeGraphs: 'Interpretar Gráficos (IA)',
    aiInterpretation: 'Interpretação IA',
    status: 'Status',
    detailedList: 'Lista Detalhada de Viabilidade',
    searchPlaceholder: 'Buscar projetos...',
    visualComparison: 'Comparativo Visual',
  },
  en: {
    dashboard: 'Dashboard',
    projectDetails: 'Project Details',
    projectSetup: 'Project Setup',
    projectSettings: 'Project Settings',
    dataInput: 'Data Input',
    reserveAnalysis: 'Reserve Analysis',
    graphicalAnalysis: 'Graphical Analysis',
    financialAnalysis: 'Economic Viability',
    comparisonBlocks: 'Comparison/Blocks',
    aiReport: 'AI Report',
    heatmap: 'Heatmap',
    statistics: 'Statistics',
    statisticalAnalysis: 'Statistical Analysis',
    gradeHistogram: 'Grade Histogram',
    gradeCurve: 'Grade-Tonnage Curve',
    boxplotStats: 'Descriptive Stats (Boxplot)',
    romAnalysis: 'ROM Analysis (Production)',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    portuguese: 'Portuguese',
    english: 'English',
    spanish: 'Spanish',
    userName: 'User Name',
    blockId: 'Block ID',
    projectName: 'Project Name',
    projectDescription: 'Project Description',
    date: 'Date',
    sampleDataTable: 'Sample Data Table',
    swellFactorSterile: 'Swell Factor (Sterile)',
    swellFactorGravel: 'Swell Factor (Gravel)',
    dilutionFactor: 'Dilution Factor (%)',
    importCSV: 'Import CSV/XLSX',
    addSample: 'Add Sample',
    validateData: 'Validate Data',
    no: '#',
    line: 'Line',
    pit: 'Pit',
    sterileDepth: 'Sterile (m)',
    gravelDepth: 'Gravel (m)',
    area: 'Area (m²)',
    volume: 'Volume (m³)',
    stones: 'Stones',
    carats: 'Carats',
    actions: 'Actions',
    remove: 'Remove',
    estimatedReserves: 'Estimated Reserves',
    prospectingData: 'Prospecting Data',
    totalPitArea: 'Total Pit Area (m²)',
    avgSterileDepth: 'Avg. Sterile Depth (m)',
    avgGravelDepth: 'Avg. Gravel Depth (m)',
    totalStones: 'Total Stones',
    totalCarats: 'Total Carats',
    stonesPerSqm: 'Stones/m²',
    avgStoneSize: 'Avg. Stone Size (ct)',
    inSituReserves: 'In Situ Reserves',
    sterileVolume: 'Sterile Volume (m³)',
    gravelVolume: 'Gravel Volume (m³)',
    estimatedCarats: 'Estimated Carats',
    caratsPerSqm: 'Carats/m²',
    caratsPerCbm: 'Carats/m³',
    estimatedStones: 'Estimated Stones',
    swelledDilutedReserves: 'Swelled & Diluted Reserves',
    swelledSterileVolume: 'Swelled Sterile Volume (m³)',
    swelledGravelVolume: 'Swelled Gravel Volume (m³)',
    avgGrade: 'Avg. Grade (ct/m³)',
    stripRatio: 'Strip Ratio (S/R)',
    chartsAndSensitivity: 'Charts & Sensitivity',
    volumeComparison: 'Volume Comparison (In Situ vs Swelled)',
    inSitu: 'In Situ',
    swelled: 'Swelled',
    sterile: 'Sterile',
    gravel: 'Gravel',
    swelledReserveDistribution: 'Swelled Reserve Distribution',
    gradeVariationByPit: 'Grade Variation by Pit (ct/m³)',
    gradeVsGravelDepth: 'Grade (ct/m³) vs. Gravel Depth (m)',
    gradeVsArea: 'Grade (ct/m³) vs. Area (m²)',
    economicParameters: 'Economic Parameters',
    diamondPrice: 'Avg. Diamond Price (USD/ct)',
    sterileRemovalCost: 'Sterile Removal Cost (USD/m³)',
    gravelTransportCost: 'Gravel Transport Cost (USD/m³/km)',
    processingCost: 'Processing Cost (USD/m³)',
    transportDistance: 'Distance to Plant (km)',
    recoveryRate: 'Recovery Rate (%)',
    blockEconomy: 'Block Economy',
    recoveredCarats: 'Recovered Carats',
    estimatedRevenue: 'Estimated Revenue (USD)',
    totalCost: 'Total Cost (USD)',
    estimatedProfit: 'Estimated Profit (USD)',
    economicViability: 'Economic Viability',
    projectViable: 'Project Viable',
    projectNotViable: 'Project Not Viable',
    sensitivityAnalysis: 'Sensitivity Analysis',
    generateReport: 'Generate AI Report',
    generating: 'Generating...',
    report: 'Report',
    copyToClipboard: 'Copy to Clipboard',
    copied: 'Copied!',
    mineralReserveReportFor: 'Mineral Reserve Report for',
    totalBlockArea: 'Total Block Area (m²)',
    geotechnicalParameters: 'Geotechnical Parameters',
    save: 'Save',
    saved: 'Saved!',
    manageProjects: 'Manage Projects',
    newProject: 'New Project',
    saveProject: 'Save Project',
    deleteProject: 'Delete Project',
    confirmDelete: 'Are you sure you want to delete this project?',
    creatingNewProject: 'Creating New Project',
    editingProject: 'Editing Project',
    chartSettings: 'Chart Settings',
    chartColors: 'Chart Colors',
    showTooltips: 'Show Tooltips',
    inSituColor: 'In Situ Color',
    swelledColor: 'Swelled Color',
    sterileColor: 'Sterile Color',
    gravelColor: 'Gravel Color',
    gradeColor: 'Grade Color',
    scatterDepthColor: 'Scatter Color (Depth)',
    scatterAreaColor: 'Scatter Color (Area)',
    reset: 'Reset',
    edit: 'Edit',
    unsavedChanges: 'Unsaved changes',
    saveChanges: 'Save Changes',
    discardChanges: 'Discard',
    confirmNavigation: 'You have unsaved changes. Do you want to save or discard them before leaving?',
    bulkEdit: 'Bulk Edit',
    selectField: 'Select Field',
    operation: 'Operation',
    setValue: 'Set Value',
    addValue: 'Add Value',
    apply: 'Apply',
    currency: 'Currency',
    unitSystem: 'Unit System',
    metric: 'Metric',
    imperial: 'Imperial',
    defaultCurrency: 'Default Currency',
    economicComparison: 'Economic Comparison',
    profitabilityComparison: 'Profitability Comparison',
    revenue: 'Revenue',
    cost: 'Cost',
    profit: 'Profit',
    roi: 'Return (ROI %)',
    loadingData: 'Loading Data...',
    selectProjectsToCompare: 'Select Projects to Compare',
    copyData: 'Copy Data (CSV)',
    analyzeGraphs: 'Analyze Graphs (AI)',
    aiInterpretation: 'AI Interpretation',
    status: 'Status',
    detailedList: 'Detailed Viability List',
    searchPlaceholder: 'Search projects...',
    visualComparison: 'Visual Comparison',
  },
  es: {
    dashboard: 'Tablero',
    projectDetails: 'Detalles del Proyecto',
    projectSetup: 'Configuración del Proyecto',
    projectSettings: 'Configuración del Proyecto',
    dataInput: 'Entrada de Datos',
    reserveAnalysis: 'Análisis de Reservas',
    graphicalAnalysis: 'Análisis Gráfico',
    financialAnalysis: 'Viabilidad Económica',
    comparisonBlocks: 'Comparación/Bloques',
    aiReport: 'Informe IA',
    heatmap: 'Mapa de Calor',
    statistics: 'Estadísticas',
    statisticalAnalysis: 'Análisis Estadístico',
    gradeHistogram: 'Histograma de Leyes',
    gradeCurve: 'Curva Ley-Tonelaje',
    boxplotStats: 'Estadísticas Descriptivas (Boxplot)',
    romAnalysis: 'Análisis ROM (Producción)',
    theme: 'Tema',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Oscuro',
    portuguese: 'Portugués',
    english: 'Inglés',
    spanish: 'Español',
    userName: 'Nombre de Usuario',
    blockId: 'ID del Bloque',
    projectName: 'Nombre del Proyecto',
    projectDescription: 'Descripción del Proyecto',
    date: 'Fecha',
    sampleDataTable: 'Tabla de Datos de Muestras',
    swellFactorSterile: 'Factor de Esponjamiento (Estéril)',
    swellFactorGravel: 'Factor de Esponjamiento (Grava)',
    dilutionFactor: 'Factor de Dilución (%)',
    importCSV: 'Importar CSV/XLSX',
    addSample: 'Añadir Muestra',
    validateData: 'Validar Datos',
    no: 'Nº',
    line: 'Línea',
    pit: 'Pozo',
    sterileDepth: 'Estéril (m)',
    gravelDepth: 'Grava (m)',
    area: 'Área (m²)',
    volume: 'Volumen (m³)',
    stones: 'Piedras',
    carats: 'Quilates',
    actions: 'Acciones',
    remove: 'Eliminar',
    estimatedReserves: 'Reservas Estimadas',
    prospectingData: 'Datos de Prospección',
    totalPitArea: 'Área Total de Pozos (m²)',
    avgSterileDepth: 'Espesor Medio Estéril (m)',
    avgGravelDepth: 'Espesor Medio Grava (m)',
    totalStones: 'Nº Total de Piedras',
    totalCarats: 'Quilates Totales',
    stonesPerSqm: 'Piedras/m²',
    avgStoneSize: 'Tamaño Medio de Piedra (ct)',
    inSituReserves: 'Reservas In Situ',
    sterileVolume: 'Volumen Estéril (m³)',
    gravelVolume: 'Volumen Grava (m³)',
    estimatedCarats: 'Quilates Estimados',
    caratsPerSqm: 'Quilates/m²',
    caratsPerCbm: 'Quilates/m³',
    estimatedStones: 'Nº de Piedras Estimadas',
    swelledDilutedReserves: 'Reservas Esponjadas y Diluidas',
    swelledSterileVolume: 'Volumen Estéril Esponjado (m³)',
    swelledGravelVolume: 'Volumen Grava Esponjada (m³)',
    avgGrade: 'Ley Media (ct/m³)',
    stripRatio: 'Relación Estéril/Mineral (S/R)',
    chartsAndSensitivity: 'Gráficos y Sensibilidad',
    volumeComparison: 'Comparación de Volumen (In Situ vs Esponjado)',
    inSitu: 'In Situ',
    swelled: 'Esponjado',
    sterile: 'Estéril',
    gravel: 'Grava',
    swelledReserveDistribution: 'Distribución de Reserva Esponjada',
    gradeVariationByPit: 'Variación de Ley por Pozo (ct/m³)',
    gradeVsGravelDepth: 'Ley (ct/m³) vs. Espesor Grava (m)',
    gradeVsArea: 'Ley (ct/m³) vs. Área (m²)',
    economicParameters: 'Parámetros Económicos',
    diamondPrice: 'Precio Medio del Diamante (USD/ct)',
    sterileRemovalCost: 'Costo Remoción Estéril (USD/m³)',
    gravelTransportCost: 'Costo Transporte Grava (USD/m³/km)',
    processingCost: 'Costo Procesamiento (USD/m³)',
    transportDistance: 'Distancia a Planta (km)',
    recoveryRate: 'Tasa de Recuperación (%)',
    blockEconomy: 'Economía del Bloque',
    recoveredCarats: 'Quilates Recuperados',
    ingresosEstimados: 'Ingresos Estimados (USD)',
    totalCost: 'Costo Total (USD)',
    estimatedProfit: 'Beneficio Estimado (USD)',
    economicViability: 'Viabilidad Económica',
    projectViable: 'Proyecto Viable',
    projectNotViable: 'Proyecto No Viable',
    sensitivityAnalysis: 'Análisis de Sensibilidad',
    generateReport: 'Generar Informe IA',
    generating: 'Generando...',
    report: 'Informe',
    copyToClipboard: 'Copiar al Portapapeles',
    copied: '¡Copiado!',
    mineralReserveReportFor: 'Informe de Reserva Mineral para',
    totalBlockArea: 'Área Total del Bloque (m²)',
    geotechnicalParameters: 'Parámetros Geotécnicos',
    save: 'Guardar',
    saved: '¡Guardado!',
    manageProjects: 'Administrar Proyectos',
    newProject: 'Nuevo Proyecto',
    saveProject: 'Guardar Proyecto',
    deleteProject: 'Eliminar Proyecto',
    confirmDelete: '¿Estás seguro de que quieres eliminar este proyecto?',
    creatingNewProject: 'Creando Nuevo Proyecto',
    editingProject: 'Editando Proyecto',
    chartSettings: 'Configuración de Gráficos',
    chartColors: 'Colores de Gráficos',
    showTooltips: 'Mostrar Información',
    inSituColor: 'Color In Situ',
    swelledColor: 'Color Esponjado',
    sterileColor: 'Color Estéril',
    gravelColor: 'Color Grava',
    gradeColor: 'Color de Ley',
    scatterDepthColor: 'Color Dispersión (Profundidad)',
    scatterAreaColor: 'Color Dispersión (Área)',
    reset: 'Reiniciar',
    edit: 'Editar',
    unsavedChanges: 'Cambios no guardados',
    saveChanges: 'Guardar Cambios',
    discardChanges: 'Descartar',
    confirmNavigation: 'Tienes cambios no guardados. ¿Deseas guardarlos o descartarlos antes de salir?',
    bulkEdit: 'Edición Masiva',
    selectField: 'Seleccionar Campo',
    operation: 'Operación',
    setValue: 'Establecer Valor',
    addValue: 'Añadir',
    apply: 'Aplicar',
    currency: 'Moneda',
    unitSystem: 'Sistema de Unidades',
    metric: 'Métrico',
    imperial: 'Imperial',
    defaultCurrency: 'Moneda Predeterminada',
    economicComparison: 'Comparación Económica',
    profitabilityComparison: 'Comparación de Rentabilidad',
    revenue: 'Ingresos',
    cost: 'Costo',
    profit: 'Beneficio',
    roi: 'Retorno (ROI %)',
    loadingData: 'Cargando Datos...',
    selectProjectsToCompare: 'Seleccionar Proyectos para Comparar',
    copyData: 'Copiar Datos (CSV)',
    analyzeGraphs: 'Analizar Gráficos (IA)',
    aiInterpretation: 'Interpretación IA',
    status: 'Estado',
    detailedList: 'Lista Detallada de Viabilidad',
    searchPlaceholder: 'Buscar proyectos...',
    visualComparison: 'Comparación Visual',
  },
};